export const fakePosts = [
	{
		author: 'John Doe',
		title: 'Fat monster',
		bio: 'This is a fat monster with green eyes',
		tags: ['fat', 'green', 'monster'],
		id: 1,
	},
	{
		author: 'Jane Smith',
		title: 'Scary monster',
		bio: 'This is a scary monster with red eyes',
		tags: ['scary', 'red', 'monster'],
		id: 2,
	},
	{
		author: 'Mike Johnson',
		title: 'Friendly monster',
		bio: 'This is a friendly monster with blue eyes',
		tags: ['friendly', 'blue', 'monster'],
		id: 3,
	},
	{
		author: 'Emily Davis',
		title: 'Hairy monster',
		bio: 'This is a hairy monster with yellow eyes',
		tags: ['hairy', 'yellow', 'monster'],
		id: 4,
	},
	{
		author: 'Chris Brown',
		title: 'Tiny monster',
		bio: 'This is a tiny monster with purple eyes',
		tags: ['tiny', 'purple', 'monster'],
		id: 5,
	},
	{
		author: 'Patricia Wilson',
		title: 'Giant monster',
		bio: 'This is a giant monster with orange eyes',
		tags: ['giant', 'orange', 'monster'],
		id: 6,
	},
	{
		author: 'Robert Martinez',
		title: 'Invisible monster',
		bio: 'This is an invisible monster with white eyes',
		tags: ['invisible', 'white', 'monster'],
		id: 7,
	},
	{
		author: 'Linda Anderson',
		title: 'Flying monster',
		bio: 'This is a flying monster with black eyes',
		tags: ['flying', 'black', 'monster'],
		id: 8,
	},
	{
		author: 'David Thomas',
		title: 'Underwater monster',
		bio: 'This is an underwater monster with green eyes',
		tags: ['underwater', 'green', 'monster'],
		id: 9,
	},
	{
		author: 'Barbara Jackson',
		title: 'Fire monster',
		bio: 'This is a fire monster with red eyes',
		tags: ['fire', 'red', 'monster'],
		id: 10,
	},
	{
		author: 'James White',
		title: 'Ice monster',
		bio: 'This is an ice monster with blue eyes',
		tags: ['ice', 'blue', 'monster'],
		id: 11,
	},
];
