export const fakePosts = [
	{
		author: 'John Doe',
		title: 'Amazing sunset at the beach 🌅',
		body: 'Spent the evening at the beach and watched the most beautiful sunset. The colors were unreal! Definitely a moment to remember. 🌊',
		tags: ['sunset', 'beach', 'nature'],
		id: 1,
	},
	{
		author: 'Jane Smith',
		title: 'New recipe experiment 🍳🔥',
		body: 'Tried a new recipe today and it turned out amazing! It’s a simple pasta dish with garlic, cherry tomatoes, and a bit of basil. So easy but so delicious! 🍝',
		tags: ['recipe', 'foodie', 'homecooking'],
		id: 2,
	},
	{
		author: 'Mike Johnson',
		title: 'Weekend hike through the mountains 🏞️',
		body: 'Just came back from a challenging but rewarding hike through the mountains. The view from the top was totally worth it. Can’t wait to do it again! ⛰️',
		tags: ['hiking', 'adventure', 'mountains'],
		id: 3,
	},
	{
		author: 'Emily Davis',
		title: 'Caught up with old friends over coffee ☕💬',
		body: 'Had the best time catching up with some old friends today. We chatted for hours over coffee and it was like no time had passed at all. 💛',
		tags: ['friendship', 'coffee', 'catchup'],
		id: 4,
	},
	{
		author: 'Chris Brown',
		title: 'Finally finished that book 📚🎉',
		body: 'After weeks of reading, I finally finished "The Great Gatsby". Such a captivating story! Can’t believe I waited so long to pick it up. Highly recommend it!',
		tags: ['reading', 'books', 'literature'],
		id: 5,
	},
	{
		author: 'Patricia Wilson',
		title: 'Tried yoga for the first time 🧘‍♀️',
		body: 'Just finished my first yoga class and I feel amazing! It was tough but so calming. I think I’m hooked. Definitely going to make this part of my routine! 🌸',
		tags: ['yoga', 'wellness', 'fitness'],
		id: 6,
	},
	{
		author: 'Robert Martinez',
		title: 'Started a new hobby – painting 🎨',
		body: 'I’ve always wanted to try painting, so I finally got some supplies and started today. It’s harder than I thought, but I’m loving it! Here’s my first attempt! 🎨🖌️',
		tags: ['painting', 'art', 'hobbies'],
		id: 7,
	},
	{
		author: 'Linda Anderson',
		title: 'Weekend getaway to the city 🚗🏙️',
		body: 'Took a short road trip to the city for the weekend and had the best time exploring new places. From museums to food trucks, it was a blast! 😎',
		tags: ['travel', 'citylife', 'getaway'],
		id: 8,
	},
	{
		author: 'David Thomas',
		title: 'My new morning routine 🕖',
		body: 'I’ve been waking up earlier and starting my day with a morning routine that includes meditation, a good breakfast, and some journaling. It’s been a game changer! 🌞',
		tags: ['morningroutine', 'selfcare', 'productivity'],
		id: 9,
	},
	{
		author: 'Barbara Jackson',
		title: 'My first attempt at gardening 🌱',
		body: 'Started a small garden in my backyard this weekend. It’s a work in progress, but I’m so excited to see how everything grows! Fingers crossed! 🌻',
		tags: ['gardening', 'home', 'nature'],
		id: 10,
	},
	{
		author: 'James White',
		title: 'Exploring the local food scene 🍴',
		body: 'Went on a food tour today and tried some of the best dishes in town. From tacos to sushi, it was a day full of flavor! Can’t wait for the next one! 🍣🌮',
		tags: ['food', 'local', 'restaurant'],
		id: 11,
	},
];
